connector.name=iceberg
iceberg.catalog.type=hive_metastore
hive.metastore.uri=thrift://23133083thuyvan-master:9083
hive.config.resources=/etc/trino/core-site.xml,/etc/trino/hdfs-site.xml
fs.hadoop.enabled=true 

# Tối ưu performance
iceberg.file-format=PARQUET
iceberg.compression-codec=SNAPPY